openapi: 3.0.0
info:
  title: SWars API
  version: '1.0.0'
  description: API para manejar información de planetas en SWars.
paths:
  /planets:
    get:
      summary: Lista todos los planetas
      operationId: listPlanets
      tags:
        - planets
      responses:
        '200':
          description: Lista de planetas obtenida con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Planet'
        '500':
          description: Error interno del servidor

components:
  schemas:
    Planet:
      type: object
      properties:
        nombre:
          type: string
          nullable: true
        periodoRotacion:
          type: integer
          format: int64
          nullable: true
        periodoOrbital:
          type: integer
          format: int64
          nullable: true
        diametro:
          type: integer
          format: int64
          nullable: true
        clima:
          type: string
          nullable: true
        gravedad:
          type: string
          nullable: true
        terreno:
          type: string
          nullable: true
        aguaSuperficial:
          type: integer
          format: int32
          nullable: true
        poblacion:
          type: integer
          format: int64
          nullable: true
